version: '3.8'

services:
  php:
    build: .
    volumes:
      - ./:/var/www/symfony:cached
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/symfony:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-app}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts
    user: root # Exécuter en tant qu'utilisateur root pour installer des outils
    ports:
      - "8083:8080"
      - "50001:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Permettre l'accès au daemon Docker
    networks:
      - app-network
    command: >
      /bin/bash -c "apt-get update &&
                    apt-get install git -y &&
                    exec /usr/bin/tini -- /usr/local/bin/jenkins.sh"

volumes:
  database_data:
  jenkins_data:

networks:
  app-network:
    driver: bridge


